// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTY6hZdZ_lMfArxtmZ4CwAbRCzDhUjxVM',
    appId: '1:891162012839:web:2c3631d2ff465daa73ff82',
    messagingSenderId: '891162012839',
    projectId: 'andicrochett-bcb21',
    authDomain: 'andicrochett-bcb21.firebaseapp.com',
    storageBucket: 'andicrochett-bcb21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJcbZt356UvHuVuJk5iZUiKQHoUpjOws',
    appId: '1:891162012839:android:95c6b322ea13af8573ff82',
    messagingSenderId: '891162012839',
    projectId: 'andicrochett-bcb21',
    storageBucket: 'andicrochett-bcb21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZUk8s_HzYferFc2LI_7nl2Ak7jZUAaGk',
    appId: '1:891162012839:ios:f46c5b1f69251e6573ff82',
    messagingSenderId: '891162012839',
    projectId: 'andicrochett-bcb21',
    storageBucket: 'andicrochett-bcb21.firebasestorage.app',
    iosBundleId: 'com.example.andicrochett',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZUk8s_HzYferFc2LI_7nl2Ak7jZUAaGk',
    appId: '1:891162012839:ios:f46c5b1f69251e6573ff82',
    messagingSenderId: '891162012839',
    projectId: 'andicrochett-bcb21',
    storageBucket: 'andicrochett-bcb21.firebasestorage.app',
    iosBundleId: 'com.example.andicrochett',
  );

}