// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkeniLfx1Dw9jfIMvIoJJJEXeFoHXlKc',
    appId: '1:926105122586:web:6c60f552fdbf9958ee9ea3',
    messagingSenderId: '926105122586',
    projectId: 'andicrochett-8d99f',
    authDomain: 'andicrochett-8d99f.firebaseapp.com',
    storageBucket: 'andicrochett-8d99f.firebasestorage.app',
    measurementId: 'G-66WEQ1FH5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxSOYtaPPgp_rGAdx910NeUa9V0REFL04',
    appId: '1:926105122586:android:d9f3baab6001837cee9ea3',
    messagingSenderId: '926105122586',
    projectId: 'andicrochett-8d99f',
    storageBucket: 'andicrochett-8d99f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQyOvjMELJUwrTyvV1MSHGag67Mj7QxIs',
    appId: '1:926105122586:ios:154b4c2e719fc3b5ee9ea3',
    messagingSenderId: '926105122586',
    projectId: 'andicrochett-8d99f',
    storageBucket: 'andicrochett-8d99f.firebasestorage.app',
    iosBundleId: 'com.example.andicrochett',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQyOvjMELJUwrTyvV1MSHGag67Mj7QxIs',
    appId: '1:926105122586:ios:154b4c2e719fc3b5ee9ea3',
    messagingSenderId: '926105122586',
    projectId: 'andicrochett-8d99f',
    storageBucket: 'andicrochett-8d99f.firebasestorage.app',
    iosBundleId: 'com.example.andicrochett',
  );
}
